spring:
  datasource:
    password: 0103
    username: root
    url: jdbc:mysql://localhost:3306/apig?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:   # 如果有密码，填上
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 100  # 调整为压测线程数的1-1.5倍
        max-idle: 50      # 约为max-active的50-70%
        min-idle: 20      # 适当提高保持的连接数
        max-wait: 500ms      # 减少等待时间，快速失败
      timeout:
        connect-timeout: 500ms
        command-timeout: 300ms  # 添加命令超时控制

  config:
    import: classpath:ratelimit.yml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.example.entity

#日志配置
logging:
  config: classpath:logback-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
